version: "3"

services:
  dd_server:
    build: .
    command: "8000" # this is the port and is required as the first commandline argument ALWAYS
    ports: 
      - "8000:8000"
    secrets:
      - source: crt
        target: /certificate.crt
      - source: key
        target: /privateKey.key
      - source: API-key
        target: config.txt

healthcheck:
      test: ["CMD", "curl", "http://0.0.0.0:6789/status"]
      interval: 60s
      timeout: 2s
      retries: 2
      start_period: 20s
      
secrets:
  key:
    file: D:\your\own\directory\certs\customkey.key # change this if you want to use https
  crt:
    file: D:\your\own\directory\certs\customcrt.crt # change this if you want to use https
  API-key:
    file: .\config.txt # change this if you want to use a different file location/name for the API-key
  
